services:
  web:
    container_name: openingfilm-web
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/openingfilm:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /var/www/openingfilm/data:/app/prisma/data
    env_file:
      - .env
